Dedicated page for each prospect profile
Wellcode-PB/SalesWell pull request #17
Opened 2022-11-22 11:33 UTC by Daniel-Tanase

2022-11-29 13:50 UTC, S7012MY requested changes

2022-11-29 13:50 UTC, S7012MY commented on pages/api/prospect/get-by-id.tsx
> +export default async (req: NextApiRequest, res: NextApiResponse) => {
let's have a more general function named get which receives the parameter as url parameters or as json. Also, maybe we can use the same method to get a list of prospects

2022-11-29 16:34 UTC, keepcoding-tech commented on pages/api/prospect/get-by-id.tsx
> +export default async (req: NextApiRequest, res: NextApiResponse) => {
Do you mean something like "get-by-key" in which we send two parameters "key" and "value"?

2022-12-05 17:31 UTC, S7012MY commented on pages/api/prospect/get-by-id.tsx
> +export default async (req: NextApiRequest, res: NextApiResponse) => {
or maybe even pass a json

2022-12-08 10:07 UTC, S7012MY approved these changes

2022-12-08 10:07 UTC, merged