Redirect user to the "root" page
Wellcode-PB/SalesWell pull request #25
Opened 2023-04-20 14:04 UTC by BunducPaul

2023-04-21 11:54 UTC, S7012MY requested changes

2023-04-21 11:54 UTC, S7012MY commented on components/Navbar.tsx
> +          <a className='navHome'> SalesWell</a>
you have an extra space here

2023-04-24 08:55 UTC, keepcoding-tech requested changes

2023-04-24 08:55 UTC, keepcoding-tech commented on components/Navbar.tsx
> +      <Typography component="div" sx={{ flexGrow: 1 }}>
Can you get rid of this element? You don't really need two `Typography` elements here.

2023-04-24 08:55 UTC, Daniel-Tanase commented on components/Navbar.tsx
> +          <Typography variant="h6" component='a' color="inherit" sx={{ textDecoration: 'none' }}>
Let's add the `color` attribute inside the `sx` (style) attribute.

2023-04-24 08:55 UTC, Daniel-Tanase commented on components/Navbar.tsx
> -      { session ?
Why did you remove these spaces?

2023-04-24 08:55 UTC, Daniel-Tanase commented on components/Navbar.tsx
> -        </Button> }
Same here?!

2023-04-24 10:51 UTC, BunducPaul commented on components/Navbar.tsx
> +      <Typography component="div" sx={{ flexGrow: 1 }}>
If I remove it, there will be clickable empty space between the link and the buttons, which is not what I want.

2023-04-24 11:10 UTC, Daniel-Tanase requested changes

2023-04-24 11:10 UTC, Daniel-Tanase commented on package.json
> +    "next": "^12.3.4",
Please don't modify this file, a different version can affect other dependencies, so we don't want to take that risk.

2023-04-24 11:10 UTC, Daniel-Tanase commented on components/Navbar.tsx
> +      <Typography component="div" sx={{ flexGrow: 1 }}>
Ok, so how can we keep the same interface but not make the space between the text and buttons clickable?

2023-04-25 15:49 UTC, Daniel-Tanase requested changes

2023-04-25 15:49 UTC, keepcoding-tech commented on components/Navbar.tsx
> +        <Typography variant="h6" component='a' sx={{ textDecoration: 'none', color: "inherit" }}>
Write the `sx` attribute on the next line. Make sure that the line does not go more than 80 characters.
Also, the `sx` should be indented with one tab to the right if written on the next line.

2023-04-26 09:13 UTC, Daniel-Tanase approved these changes

2023-04-26 09:16 UTC, S7012MY approved these changes

2023-04-26 10:58 UTC, merged