added new features to homepage
Wellcode-PB/SalesWell pull request #32
Opened 2023-04-29 07:51 UTC by GeorgeMocanu23

2023-04-29 09:12 UTC, S7012MY requested changes

2023-04-29 09:12 UTC, S7012MY commented on pages/index.tsx
> +import { Typography } from '@mui/material';
we don't use ; in this project

2023-04-29 09:12 UTC, S7012MY commented on public/themes/welcomeTheme.js
> +import { createTheme } from '@mui/material/styles';
let's use default.js as the name of the file and theme. Or even better salesWell.js

2023-04-29 09:12 UTC, S7012MY commented on pages/index.tsx
> +        Welcome{
Please fix the indentation

2023-04-29 09:12 UTC, S7012MY commented on pages/index.tsx
> +      <Typography variant="subtitle1">
can't we use dirrectly h1/h2...?

2023-04-29 09:12 UTC, S7012MY commented on public/themes/welcomeTheme.js
> +import { createTheme } from '@mui/material/styles';
Also, are we sure we need to create a theme?

2023-05-02 09:19 UTC, keepcoding-tech requested changes

2023-05-02 09:19 UTC, Daniel-Tanase commented on pages/index.tsx
> +      { session ? ' back, ' + session.user.name + ' !' : ' to SalesWell' }
There shouldn't be a space before `!`

2023-05-02 15:33 UTC, Daniel-Tanase approved these changes

2023-05-02 15:34 UTC, S7012MY approved these changes

2023-05-02 15:35 UTC, merged