Added redirect to error page when Url is wrong
Wellcode-PB/SalesWell pull request #40
Opened 2023-05-11 14:31 UTC by CiprianDumitriu

Overview of the problem:

When entering a wrong Url or are searching for a user that doesn't exist it would still load the components but there would be no data there.

Added features:

-the user is redirected when entering wrong Url
-added loading page while the app decided what to do

2023-05-11 16:40 UTC, Daniel-Tanase requested changes

2023-05-11 16:40 UTC, Daniel-Tanase commented on pages/prospects/profile/[id].tsx
> +              <CustomError title={title} message={message}></CustomError>
Let's include the `CustomError` outside the `Paper` component

2023-05-11 16:40 UTC, Daniel-Tanase commented on pages/prospects/profile/[id].tsx
> +              <CustomError title={title} message={message}></CustomError>
Also, do you really need the `title` and `message` variables?

2023-05-12 12:51 UTC, Daniel-Tanase commented
Looks good! Now, let's get rid of all the `;` and use `'` instead of `"`. Alos, you will need to write some tests for this pull-request.

2023-05-15 14:31 UTC, S7012MY requested changes

2023-05-15 14:31 UTC, S7012MY commented on cypress/integration/prospects/profile.js
> +    for (let index = 10; index < 20; index++) {
let's just generate a random number bigger than 9 and it will be fine

2023-05-15 14:31 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
> +import CustomError from '../../../components/CustomError'
let's import components in alphabetical order based on the path

2023-05-15 14:31 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
> +import ProfileInfo from '../../../components/prospects/ProfileInfo'
newline between local imports and global ones

2023-05-15 14:31 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
> +          setIsLoading(false)
let's move this before the if in order to avoid repetitive code

2023-05-15 14:31 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
> +          {!hasError ? (
let's do an if (hasError) Return ( /* ERROR COMPONENT */ ) 
Same for loading. It will make the code easier to understand

2023-05-16 11:51 UTC, S7012MY requested changes

2023-05-16 11:51 UTC, S7012MY commented on cypress/integration/prospects/profile.js
> +    const index = Math.floor(Math.random() * 10) + 10
this should be included in a different test (you should call the it function again)

2023-05-16 11:51 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
>    return (
let's use ifs instead of ternary operators (?) and multiple return statements

2023-05-16 12:48 UTC, S7012MY requested changes

2023-05-16 12:48 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
> +  } else {
you don't need else if you already returned

2023-05-16 12:48 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
> +          ></CustomError>
instead of doing </Component>, you could just use />

2023-05-18 10:50 UTC, S7012MY requested changes
Please fix the tests

2023-05-20 10:47 UTC, S7012MY requested changes

2023-05-20 10:47 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
> +
remove extra line

2023-05-20 10:47 UTC, S7012MY commented on pages/prospects/profile/[id].tsx
> +          <Divider sx={{ width: 'auto' }} orientation='horizontal' />
use double quotes: https://stackoverflow.com/questions/44208081/js-quote-best-practices-es6-react-single-double-backticks

2023-05-22 09:50 UTC, Daniel-Tanase requested changes

2023-05-22 09:50 UTC, keepcoding-tech commented on pages/prospects/profile/[id].tsx
> +      </>
You don't really need to use `<></>` if you are returning a single element.

2023-05-22 12:26 UTC, Daniel-Tanase approved these changes

2023-05-22 12:35 UTC, S7012MY approved these changes

2023-05-22 13:40 UTC, merged