restricting a normal user or a non-logged user to create a new account
Wellcode-PB/SalesWell pull request #41
Opened 2023-05-11 16:53 UTC by GeorgeMocanu23

2023-05-12 07:42 UTC, Daniel-Tanase requested changes

2023-05-12 07:42 UTC, Daniel-Tanase commented on pages/user/generate.tsx
> +  if (!session || session.role !== 'ADMIN') {
Use ternary operators for rendering data instead of `if - else`

2023-05-12 07:42 UTC, Daniel-Tanase commented on pages/user/generate.tsx
> +        title='Access forbidden'
A better title would be `Restricted`

2023-05-12 07:42 UTC, Daniel-Tanase commented on cypress/integration/user/generate.js
> -    cy.get('input[id="password"]').click().type('test password')
Let's use `.should('not.exist')` for some of the components instead of deleting them

2023-05-12 07:42 UTC, Daniel-Tanase commented on lib/has-permissions.ts
> -      .send({ error: 'You do not have enough permissions for this action!'})
Why did you delete this?

2023-05-12 17:22 UTC, Daniel-Tanase requested changes

2023-05-12 17:22 UTC, Daniel-Tanase commented on pages/user/generate.tsx
> +        <Box component="form"
This line should be on line 54

2023-05-13 12:57 UTC, S7012MY requested changes
You shouldn't delete the generation test entirely. We need a test for checking if the admin can generate a user and another test for checking that a regular user doesn't have access to the page

2023-05-13 12:57 UTC, S7012MY requested changes
You shouldn't delete the generation test entirely. We need a test for checking if the admin can generate a user and another test for checking that a regular user doesn't have access to the page

2023-05-13 18:31 UTC, GeorgeMocanu23 commented
Well, isn't that what I did?
I don't understand why do you say "You shouldn't delete the generation test entirely".
I didn't delete the test entirely.

 I modified the list of tests with ".should('not.exist')" so that a non-logged user or a normal user cannot generate another user.  Only admin users can create new accounts.

2023-05-14 10:14 UTC, S7012MY commented
@GeorgeMocanu23 where is the piece of code that tests if an admin still has access to the generation page?

2023-05-14 10:30 UTC, GeorgeMocanu23 commented
The piece of code that tests if an admin still has access to the generation page starting from line 25 of file "generate.js".

2023-05-14 17:52 UTC, S7012MY requested changes

2023-05-14 17:52 UTC, S7012MY commented on cypress/integration/user/generate.js
>  describe('Generate users', () => {
we should have 2 tests here. One test for calling the api and getting an error, and second when on the page checking that the error is there before calling the api

2023-05-17 07:33 UTC, S7012MY requested changes

2023-05-17 07:33 UTC, S7012MY commented on cypress/integration/user/generate.js
> +    cy.request({ url: '/api/user/generate', failOnStatusCode: false })
We should do a post request here with a similar payload to what the actual app is sending so we can simulate the real behavior perfectly
Also, let's test first the interface and move this line afterwards

2023-05-17 07:33 UTC, S7012MY commented on pages/user/generate.tsx
> +      { !session || session.role !== 'ADMIN' ?
Let's return early instead of using ternary operator

2023-05-17 07:33 UTC, S7012MY commented on pages/user/generate.tsx
> +              <TextField id="mail" label="email" onChange={ handleChange } />
Let's not use spaces after { and before } : https://airbnb.io/javascript/react/

2023-05-18 10:54 UTC, S7012MY requested changes

2023-05-18 10:54 UTC, S7012MY commented on cypress/integration/user/generate.js
> +      failOnStatusCode: false
the request should also have a body in order to be identical to the real one

2023-05-18 10:54 UTC, S7012MY commented on pages/user/generate.tsx
> +import CustomError from '../../components/CustomError'
let's leave a blank line between internal and external imports

2023-05-20 10:49 UTC, S7012MY approved these changes

2023-05-20 10:50 UTC, merged