after creating a new prospect, the user will be directed to the page …
Wellcode-PB/SalesWell pull request #48
Opened 2023-06-07 13:10 UTC by GeorgeMocanu23

…where he can add notes

2023-06-07 16:07 UTC, S7012MY requested changes

2023-06-07 16:07 UTC, S7012MY commented on components/prospects/CreateProspect.tsx
> +        fetch('/api/prospect/search?input=' + prospect.mail, {
can we do it without calling fetch a second time?

2023-06-08 17:16 UTC, GeorgeMocanu23 commented on components/prospects/CreateProspect.tsx
> +        fetch('/api/prospect/search?input=' + prospect.mail, {
Surely the user can be redirected by another method, but today, all day I did not find a solution that could help me.
I notice that the 'SearchProspect' component renders 'CreateProspect' but without any parameters and I think that 'CreateProspect' should receive as a parameter the last created 'id', and then I can use it to complete the correct route.

Now I'm not sure if 'CreateProspect' should be rendered here or from another component.

A little hint would help me a lot.

2023-06-09 09:59 UTC, Daniel-Tanase requested changes

2023-06-09 09:59 UTC, Daniel-Tanase commented on cypress/integration/prospects/list.js
> +    // list, also we need to scroll all the way down 3 times to make the 21st
Let's rewrite the comment so it actually makes sense

2023-06-09 09:59 UTC, Daniel-Tanase commented on cypress/integration/prospects/list.js
>      // prospect visible
You also need to delete this comment

2023-06-09 10:07 UTC, Daniel-Tanase commented on components/prospects/CreateProspect.tsx
> +        fetch('/api/prospect/search?input=' + prospect.mail, {
I think the quickest way would be to modify the API end-point to return the `id` of the prospect too.

2023-06-09 15:34 UTC, Daniel-Tanase requested changes

2023-06-09 15:34 UTC, Daniel-Tanase commented on components/prospects/CreateProspect.tsx
>            severity: 'success',
I don't think we still need to set the message to `success` if we redirect the user anyway.

2023-06-09 15:34 UTC, Daniel-Tanase commented on pages/api/prospect/create.tsx
> +  const createdProspect = await prisma.prospects.create({ data: {
Just `prospect` I think is a good enough name

2023-06-10 10:13 UTC, S7012MY requested changes

2023-06-10 10:13 UTC, S7012MY commented on cypress/integration/prospects/list.js
> -    cy.contains('test@wellcode.com')
we should still check that the newly created prospect still appears in the list

2023-06-12 12:00 UTC, keepcoding-tech approved these changes

2023-06-12 12:06 UTC, S7012MY approved these changes

2023-06-12 16:15 UTC, merged