Add infinite scroll on prospects
Wellcode-PB/SalesWell pull request #9
Opened 2022-09-09 12:33 UTC by iLenut

2022-09-11 11:56 UTC, Daniel-Tanase requested changes

2022-09-11 11:56 UTC, Daniel-Tanase commented on pages/api/utils/get_paginated_data.tsx
> +    const data = await prisma.prospects.findMany({
let's get rid of the repetitive code :D

2022-09-11 11:56 UTC, Daniel-Tanase commented on pages/prospects/list.tsx
> +  async function getMoreProspects() {
is there a way to combine this functionality to that for bookings?

2022-09-16 12:49 UTC, S7012MY approved these changes

2022-09-16 12:49 UTC, merged